travis:
  secure:
    BINSTAR_TOKEN: ukBdHSjgD64GI2joRZV/MdlBUubC0ogh59dwngRNDBzY54BQtC7ll0rr+0W2pBFrHHB1l0bv208yyXH7N/+9Abz253fpafkrVA2Cu/NTeJZypfY5hIJnToqCv5V9J4asQHDpW57Wh0QYjNgbJu4NRagPZPy/F+tkenELtqYqTS8aBWSHDdqbWXhBuQPo9XmWuq8HkzRAnb4uZ7GIo6EFA1FYCrZ7PA1z9pcSmSKjCdW/ufz7XNxo6yhpog0yaeAwfs+/XEpSaCdqVtWUSLmFbiuJMJd0MYamOQsSg3gVs8NSbmwSoxbM0bsWoUm4uFgSY3HR+oe05aW5seyX2tdDt9d1r7yr+u0drAwJxSlx8ARZvEls+M2qKK7OLvfAY3KWC8Q0/yW1xU6+6pobFW1EGEii9BDMk1JE12Xx9+rGf/s2VHsGXMd3gLtTTQKeocL+eQsKWubzGlHB8Q+rAY9s4QxqHVywxCE+Z8X/ekj4BDIjLCVjr1OcQacGDKYo4UktSd/QHOCjhSUz0OykdAq+XeaOS27gNtuu1UQe42cwF6q7ZNlhllzecv5BPxL6sCPB5C3RqNaxlnOWyM72Hl3RZF2dog+3FIpcvir2YHm0mnRtBnHxNnrKvKNS42ncjjmm9Ld/btL1KUwIb7+BGSWL4PhvILW/5lmG8MIqjAF8Ov0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
