travis:
  secure:
    BINSTAR_TOKEN: ryR7/eQT6Auhtp56NyP1Bl1rHOmtB16HRTiLL/OOpDjbNXg8KPH5c1m2hOFeXeltHNFyrIpEzOGZ7kBa2feu3xxTv6HdfFuyzzYkxlLeq1K+Vee4RrXSuSOwYTjCn+DIVMlWj1IVYQlHqqxTw8BR/2eLwTyvB0AkpA+wwLX0TsoUgqhr3qfDNDjitMgvvamMJVv6Dr19FTuP4T2iANIbPjNCZV+rSNxkkftTCzrJTY3o+VitEbCJBYd1B2DE35RzN0yi3XsfeUO6Sk3PxwhCEh1wnUDihXUehgbN0h5h18zH/+mZNzfEiLcZ4ubFyEb5mKU4xhN5XM91wwUHTE+bniHDWupVQRr9/gnoA12iNtmmK8pBxa54BUBsrO9dDe9WWFmS7dn/2QUtCKZWYb7LfTXRUQ80vuD5ELTcUAyg9nY7ONi121zW2Xik9fo8IWkw5JmQH/YfqRFN/dUAV8YJQJiA8eJe1VSJwBWdDKTYIemuYXum+aDLmFYbL1IDObAXJ6xGaXU/KbKfFKCQpzk90SJxrrPNJsBPenXf38hM//luTZsVqdfNzCEK4/urkOZd1YQTUrpmq69pSEfJk5h4Nl8Vc7KnyAgb5waRQVmwT2PUI0eWYV0eeL4+BCUjbkgk9fwTSksKyrIpXkqX5eVWChSDOwhiThDDmtN/u/X/Myg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
