travis:
  secure:
    BINSTAR_TOKEN: WYPRIYDXh+DQiTEbQLz0EMf1sYKczfzrBC0wBnMh2qsK3scr0fcllddGHnxfDN6Lxw+JDuV7Cozs7lseqLiIiRWlOZMt4cDhkDurBCBbflWR+dlLriwhH/uRmZ6nCZb5yK+r5ovdDe54lcp4kHex6LYmS0477WyYhKwnzpwxLdB/Zsr7KcEfw1Mks36AJIa+vV9K7zrN7VBKgPo/qIzKB3ADT18AGnCC/5QAePpPLzFRkIFKWrNyq3ugP8Riby/L2XFtId3vO2KYB04pognSp6biAAt8RPK6Q85/889ygGJYuvU0jmiL9O/qEjq95d0EGeC5zdrpEXQFotEzdefHUVbe4+LQFbvJXmrGho26kX30WHCTtBMKK/tIpK9A5oBEo0MXuEtosCqheAXvnU+5n1nT+M8yvJQWK368PI1zqf3uRtYZu3sD5eeAiQPnC2T2ir1VL+dZgiD5gs5TgvSWocWvyRgKKzZAy84PGCA57b7p6VR3rorjWvLkK664jWZ3OmSFbneUpDLnekXl3Wz7L+tQy57nDRiVAlFCnZ+LucQQDIReBQ2eKiZpU7k3mweyaq/dAzt2vBw9NKosYwNTBofOhBzHLMmDavmSz3xP7FTXtRO28v3ULws/CDlppNCi9QKfKMzA2hsH0GVtYOC4dGqJg3+VOOI1z/1+dcAWw6o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
